minimum_pre_commit_version: "3.0"
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.5.1'
  hooks:
  - id: ruff
  - id: ruff-format
  files: ^src/.*\.py$
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.0
  hooks:
  - id: check-github-workflows
    # files: .gitlab-ci.yml
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.29.0
  hooks:
  - id: yamllint
    args: [-d relaxed]
    verbose: true
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    # for args see https://mypy.readthedocs.io/en/stable/command_line.html
